--------------------------------------------------------
--  File created - Wednesday-August-05-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SECTION
--------------------------------------------------------

  CREATE TABLE "S201224780"."SECTION" 
   (	"REFRENCE_NUMBER" VARCHAR2(11 BYTE), 
	"number" NUMBER(2,0), 
	"INSTRUCTOR_ID" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "S201224780"."DEPARTMENT" 
   (	"ID" VARCHAR2(1 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"ABBREVIATION" VARCHAR2(5 BYTE), 
	"COLLEGE_ID" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COLLEGE
--------------------------------------------------------

  CREATE TABLE "S201224780"."COLLEGE" 
   (	"ID" VARCHAR2(1 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"ABBREVIATION" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POINT
--------------------------------------------------------

  CREATE TABLE "S201224780"."POINT" 
   (	"EARNED_POINTS" NUMBER(3,0), 
	"GRADING_COMPONENT_ID" NUMBER(3,0), 
	"ENROLLMENT_STUDENT_ID" NUMBER(9,0), 
	"ENROLLMENT_REFRENCE_NUMBER" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GRADING_COMPONENT
--------------------------------------------------------

  CREATE TABLE "S201224780"."GRADING_COMPONENT" 
   (	"ID" NUMBER(3,0), 
	"NAME" VARCHAR2(15 BYTE), 
	"MAX_POINTS" NUMBER(3,0), 
	"WEIGHT" NUMBER(2,0), 
	"COURSE_NUMBER" NUMBER(4,0), 
	"INSTRUCTOR_ID" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "S201224780"."STUDENT" 
   (	"ID" NUMBER(9,0), 
	"FIRST_NAME" VARCHAR2(15 BYTE), 
	"LAST_NAME" VARCHAR2(15 BYTE), 
	"MAJOR_CODE" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENROLLMENT
--------------------------------------------------------

  CREATE TABLE "S201224780"."ENROLLMENT" 
   (	"REG_DATE" DATE, 
	"STUDENT_ID" NUMBER(9,0), 
	"SECTION_REFRENCE_NUMBER" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MAJOR
--------------------------------------------------------

  CREATE TABLE "S201224780"."MAJOR" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"CODE" VARCHAR2(4 BYTE), 
	"DEPARTMENT_ID" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INSTRUCTOR
--------------------------------------------------------

  CREATE TABLE "S201224780"."INSTRUCTOR" 
   (	"ID" NUMBER(9,0), 
	"FIRST_NAME" VARCHAR2(15 BYTE), 
	"LAST_NAME" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "S201224780"."COURSE" 
   (	"number" NUMBER(4,0), 
	"TITLE" VARCHAR2(50 BYTE), 
	"level" NUMBER(3,0), 
	"MAJOR_CODE" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into S201224780.SECTION
SET DEFINE OFF;
Insert into S201224780.SECTION (REFRENCE_NUMBER,"number",INSTRUCTOR_ID) values ('1',1,1);
REM INSERTING into S201224780.DEPARTMENT
SET DEFINE OFF;
Insert into S201224780.DEPARTMENT (ID,NAME,ABBREVIATION,COLLEGE_ID) values ('A','ICS','ICS','A');
REM INSERTING into S201224780.COLLEGE
SET DEFINE OFF;
Insert into S201224780.COLLEGE (ID,NAME,ABBREVIATION) values ('A','PC','PC');
REM INSERTING into S201224780.POINT
SET DEFINE OFF;
REM INSERTING into S201224780.GRADING_COMPONENT
SET DEFINE OFF;
REM INSERTING into S201224780.STUDENT
SET DEFINE OFF;
Insert into S201224780.STUDENT (ID,FIRST_NAME,LAST_NAME,MAJOR_CODE) values (1,'IBR','AH','ICS');
REM INSERTING into S201224780.ENROLLMENT
SET DEFINE OFF;
Insert into S201224780.ENROLLMENT (REG_DATE,STUDENT_ID,SECTION_REFRENCE_NUMBER) values (null,1,'1');
REM INSERTING into S201224780.MAJOR
SET DEFINE OFF;
Insert into S201224780.MAJOR (NAME,CODE,DEPARTMENT_ID) values ('ICS','ICS','A');
REM INSERTING into S201224780.INSTRUCTOR
SET DEFINE OFF;
Insert into S201224780.INSTRUCTOR (ID,FIRST_NAME,LAST_NAME) values (1,'IB','RA');
REM INSERTING into S201224780.COURSE
SET DEFINE OFF;
Insert into S201224780.COURSE ("number",TITLE,"level",MAJOR_CODE) values (1234,'DB',324,'ICS');
--------------------------------------------------------
--  DDL for Index SECTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S201224780"."SECTION_PK" ON "S201224780"."SECTION" ("REFRENCE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S201224780"."DEPARTMENT_PK" ON "S201224780"."DEPARTMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COLLEGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S201224780"."COLLEGE_PK" ON "S201224780"."COLLEGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GRADING_COMPONENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S201224780"."GRADING_COMPONENT_PK" ON "S201224780"."GRADING_COMPONENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S201224780"."STUDENT_PK" ON "S201224780"."STUDENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENROLLMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S201224780"."ENROLLMENT_PK" ON "S201224780"."ENROLLMENT" ("STUDENT_ID", "SECTION_REFRENCE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MAJOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S201224780"."MAJOR_PK" ON "S201224780"."MAJOR" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INSTRUCTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S201224780"."INSTRUCTOR_PK" ON "S201224780"."INSTRUCTOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "S201224780"."COURSE_PK" ON "S201224780"."COURSE" ("number") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SECTION
--------------------------------------------------------

  ALTER TABLE "S201224780"."SECTION" ADD CONSTRAINT "SECTION_PK" PRIMARY KEY ("REFRENCE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "S201224780"."SECTION" MODIFY ("INSTRUCTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "S201224780"."SECTION" MODIFY ("REFRENCE_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "S201224780"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "S201224780"."DEPARTMENT" MODIFY ("COLLEGE_ID" NOT NULL ENABLE);
  ALTER TABLE "S201224780"."DEPARTMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLLEGE
--------------------------------------------------------

  ALTER TABLE "S201224780"."COLLEGE" ADD CONSTRAINT "COLLEGE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "S201224780"."COLLEGE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POINT
--------------------------------------------------------

  ALTER TABLE "S201224780"."POINT" MODIFY ("ENROLLMENT_REFRENCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "S201224780"."POINT" MODIFY ("ENROLLMENT_STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "S201224780"."POINT" MODIFY ("GRADING_COMPONENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRADING_COMPONENT
--------------------------------------------------------

  ALTER TABLE "S201224780"."GRADING_COMPONENT" ADD CONSTRAINT "GRADING_COMPONENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "S201224780"."GRADING_COMPONENT" MODIFY ("INSTRUCTOR_ID" NOT NULL ENABLE);
  ALTER TABLE "S201224780"."GRADING_COMPONENT" MODIFY ("COURSE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "S201224780"."GRADING_COMPONENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "S201224780"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "S201224780"."STUDENT" MODIFY ("MAJOR_CODE" NOT NULL ENABLE);
  ALTER TABLE "S201224780"."STUDENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENROLLMENT
--------------------------------------------------------

  ALTER TABLE "S201224780"."ENROLLMENT" ADD CONSTRAINT "ENROLLMENT_PK" PRIMARY KEY ("STUDENT_ID", "SECTION_REFRENCE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "S201224780"."ENROLLMENT" MODIFY ("SECTION_REFRENCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "S201224780"."ENROLLMENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAJOR
--------------------------------------------------------

  ALTER TABLE "S201224780"."MAJOR" ADD CONSTRAINT "MAJOR_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "S201224780"."MAJOR" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "S201224780"."MAJOR" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "S201224780"."INSTRUCTOR" ADD CONSTRAINT "INSTRUCTOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "S201224780"."INSTRUCTOR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "S201224780"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("number")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "S201224780"."COURSE" MODIFY ("MAJOR_CODE" NOT NULL ENABLE);
  ALTER TABLE "S201224780"."COURSE" MODIFY ("number" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SECTION
--------------------------------------------------------

  ALTER TABLE "S201224780"."SECTION" ADD CONSTRAINT "SECTION_INSTRUCTOR_FK" FOREIGN KEY ("INSTRUCTOR_ID")
	  REFERENCES "S201224780"."INSTRUCTOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "S201224780"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_COLLEGE_FK" FOREIGN KEY ("COLLEGE_ID")
	  REFERENCES "S201224780"."COLLEGE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POINT
--------------------------------------------------------

  ALTER TABLE "S201224780"."POINT" ADD CONSTRAINT "POINT_ENROLLMENT_FK" FOREIGN KEY ("ENROLLMENT_STUDENT_ID", "ENROLLMENT_REFRENCE_NUMBER")
	  REFERENCES "S201224780"."ENROLLMENT" ("STUDENT_ID", "SECTION_REFRENCE_NUMBER") ON DELETE CASCADE ENABLE;
  ALTER TABLE "S201224780"."POINT" ADD CONSTRAINT "POINT_GRADING_COMP_FK" FOREIGN KEY ("GRADING_COMPONENT_ID")
	  REFERENCES "S201224780"."GRADING_COMPONENT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRADING_COMPONENT
--------------------------------------------------------

  ALTER TABLE "S201224780"."GRADING_COMPONENT" ADD CONSTRAINT "GRADING_COMP_COURSE_FK" FOREIGN KEY ("COURSE_NUMBER")
	  REFERENCES "S201224780"."COURSE" ("number") ON DELETE CASCADE ENABLE;
  ALTER TABLE "S201224780"."GRADING_COMPONENT" ADD CONSTRAINT "GRADING_COMP_INST_FK" FOREIGN KEY ("INSTRUCTOR_ID")
	  REFERENCES "S201224780"."INSTRUCTOR" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "S201224780"."STUDENT" ADD CONSTRAINT "STUDENT_MAJOR_FK" FOREIGN KEY ("MAJOR_CODE")
	  REFERENCES "S201224780"."MAJOR" ("CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENROLLMENT
--------------------------------------------------------

  ALTER TABLE "S201224780"."ENROLLMENT" ADD CONSTRAINT "ENROLL_SECTION_FK" FOREIGN KEY ("SECTION_REFRENCE_NUMBER")
	  REFERENCES "S201224780"."SECTION" ("REFRENCE_NUMBER") ON DELETE CASCADE ENABLE;
  ALTER TABLE "S201224780"."ENROLLMENT" ADD CONSTRAINT "ENROLL_STUDENT_FK" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "S201224780"."STUDENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAJOR
--------------------------------------------------------

  ALTER TABLE "S201224780"."MAJOR" ADD CONSTRAINT "MAJOR_DEPARTMENT_FK" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "S201224780"."DEPARTMENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "S201224780"."COURSE" ADD CONSTRAINT "COURSE_MAJOR_FK" FOREIGN KEY ("MAJOR_CODE")
	  REFERENCES "S201224780"."MAJOR" ("CODE") ON DELETE CASCADE ENABLE;
